# Generated by Django 3.2.12 on 2022-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name *')),
                ('product_details', models.CharField(max_length=500, verbose_name='Product Details *')),
                ('price', models.IntegerField(default=0, max_length=5, verbose_name='Price (INR) *')),
                ('discount', models.IntegerField(default=0, max_length=5, verbose_name='Discounted Price (INR)')),
                ('product_image', models.ImageField(upload_to='media/', verbose_name='Product Image *')),
                ('featured', models.BooleanField(default='', verbose_name='Featured')),
                ('in_stock', models.BooleanField(default='', verbose_name='In Stock')),
            ],
        ),
    ]
