# Generated by Django 3.2.12 on 2022-02-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default='', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_out',
            field=models.BooleanField(default='', verbose_name='Out of Stock'),
        ),
    ]
