# Generated by Django 3.2.12 on 2022-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstoreapp', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-in_stock',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In Stock'),
        ),
    ]
